/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_MSH = 1,
  sym_segment_name = 2,
  sym_field_separator = 3,
  sym_component_separator = 4,
  sym_repetition_separator = 5,
  sym_escape_character = 6,
  sym_subcomponent_separator = 7,
  anon_sym_CR = 8,
  anon_sym_LF = 9,
  anon_sym_CR_LF = 10,
  sym_number = 11,
  sym_string = 12,
  sym_message = 13,
  sym_msh = 14,
  sym_msh_controls = 15,
  sym_segment = 16,
  sym_segment_separator = 17,
  sym_field = 18,
  sym_repeat = 19,
  sym_component = 20,
  sym_subcomponent = 21,
  aux_sym_message_repeat1 = 22,
  aux_sym_msh_repeat1 = 23,
  aux_sym_field_repeat1 = 24,
  aux_sym_repeat_repeat1 = 25,
  aux_sym_component_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_MSH] = "MSH",
  [sym_segment_name] = "segment_name",
  [sym_field_separator] = "field_separator",
  [sym_component_separator] = "component_separator",
  [sym_repetition_separator] = "repetition_separator",
  [sym_escape_character] = "escape_character",
  [sym_subcomponent_separator] = "subcomponent_separator",
  [anon_sym_CR] = "\r",
  [anon_sym_LF] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_message] = "message",
  [sym_msh] = "msh",
  [sym_msh_controls] = "msh_controls",
  [sym_segment] = "segment",
  [sym_segment_separator] = "segment_separator",
  [sym_field] = "field",
  [sym_repeat] = "repeat",
  [sym_component] = "component",
  [sym_subcomponent] = "subcomponent",
  [aux_sym_message_repeat1] = "message_repeat1",
  [aux_sym_msh_repeat1] = "msh_repeat1",
  [aux_sym_field_repeat1] = "field_repeat1",
  [aux_sym_repeat_repeat1] = "repeat_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_MSH] = anon_sym_MSH,
  [sym_segment_name] = sym_segment_name,
  [sym_field_separator] = sym_field_separator,
  [sym_component_separator] = sym_component_separator,
  [sym_repetition_separator] = sym_repetition_separator,
  [sym_escape_character] = sym_escape_character,
  [sym_subcomponent_separator] = sym_subcomponent_separator,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_message] = sym_message,
  [sym_msh] = sym_msh,
  [sym_msh_controls] = sym_msh_controls,
  [sym_segment] = sym_segment,
  [sym_segment_separator] = sym_segment_separator,
  [sym_field] = sym_field,
  [sym_repeat] = sym_repeat,
  [sym_component] = sym_component,
  [sym_subcomponent] = sym_subcomponent,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
  [aux_sym_msh_repeat1] = aux_sym_msh_repeat1,
  [aux_sym_field_repeat1] = aux_sym_field_repeat1,
  [aux_sym_repeat_repeat1] = aux_sym_repeat_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_MSH] = {
    .visible = true,
    .named = false,
  },
  [sym_segment_name] = {
    .visible = true,
    .named = true,
  },
  [sym_field_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_component_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_repetition_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_character] = {
    .visible = true,
    .named = true,
  },
  [sym_subcomponent_separator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_msh] = {
    .visible = true,
    .named = true,
  },
  [sym_msh_controls] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_segment_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_repeat] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_subcomponent] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_msh_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_repeat_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '&') ADVANCE(20);
      if (lookahead == 'M') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead == '^') ADVANCE(17);
      if (lookahead == '|') ADVANCE(16);
      if (lookahead == '~') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 23,
        '\r', 21,
        '&', 20,
        '^', 17,
        '|', 16,
        '~', 18,
        '\t', 29,
        0x0b, 29,
        '\f', 29,
        ' ', 29,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == '&') ADVANCE(20);
      if (lookahead == '^') ADVANCE(17);
      if (lookahead == '|') ADVANCE(16);
      if (lookahead == '~') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == 'H') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'H') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'M') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'S') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'S') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == '^') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\\' &&
          lookahead != '|' &&
          lookahead != '~') ADVANCE(31);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_MSH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_segment_name);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_segment_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_field_separator);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_component_separator);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_repetition_separator);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_escape_character);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_subcomponent_separator);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '&' &&
          lookahead != '\\' &&
          lookahead != '^' &&
          lookahead != '|' &&
          lookahead != '~') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\\' &&
          lookahead != '^' &&
          lookahead != '|' &&
          lookahead != '~') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '&' &&
          lookahead != '\\' &&
          lookahead != '^' &&
          lookahead != '|' &&
          lookahead != '~') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '&' &&
          lookahead != '\\' &&
          lookahead != '^' &&
          lookahead != '|' &&
          lookahead != '~') ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_MSH] = ACTIONS(1),
    [sym_segment_name] = ACTIONS(1),
    [sym_field_separator] = ACTIONS(1),
    [sym_component_separator] = ACTIONS(1),
    [sym_repetition_separator] = ACTIONS(1),
    [sym_escape_character] = ACTIONS(1),
    [sym_subcomponent_separator] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_message] = STATE(36),
    [sym_msh] = STATE(27),
    [anon_sym_MSH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      sym_component_separator,
    STATE(5), 1,
      sym_subcomponent,
    STATE(10), 1,
      sym_component,
    STATE(11), 1,
      aux_sym_repeat_repeat1,
    STATE(18), 1,
      sym_repeat,
    STATE(26), 1,
      sym_field,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
    ACTIONS(5), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [29] = 4,
    STATE(5), 1,
      sym_subcomponent,
    STATE(21), 1,
      sym_component,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
    ACTIONS(11), 6,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [48] = 3,
    STATE(14), 1,
      sym_subcomponent,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
    ACTIONS(13), 7,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      sym_subcomponent_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [65] = 3,
    ACTIONS(17), 1,
      sym_subcomponent_separator,
    STATE(6), 1,
      aux_sym_component_repeat1,
    ACTIONS(15), 6,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [80] = 3,
    ACTIONS(17), 1,
      sym_subcomponent_separator,
    STATE(7), 1,
      aux_sym_component_repeat1,
    ACTIONS(19), 6,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [95] = 3,
    ACTIONS(23), 1,
      sym_subcomponent_separator,
    STATE(7), 1,
      aux_sym_component_repeat1,
    ACTIONS(21), 6,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [110] = 3,
    ACTIONS(28), 1,
      sym_component_separator,
    STATE(8), 1,
      aux_sym_repeat_repeat1,
    ACTIONS(26), 5,
      sym_field_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [124] = 1,
    ACTIONS(31), 7,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      sym_subcomponent_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [134] = 3,
    ACTIONS(7), 1,
      sym_component_separator,
    STATE(13), 1,
      aux_sym_repeat_repeat1,
    ACTIONS(33), 5,
      sym_field_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [148] = 3,
    ACTIONS(7), 1,
      sym_component_separator,
    STATE(8), 1,
      aux_sym_repeat_repeat1,
    ACTIONS(33), 5,
      sym_field_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [162] = 6,
    ACTIONS(7), 1,
      sym_component_separator,
    STATE(5), 1,
      sym_subcomponent,
    STATE(10), 1,
      sym_component,
    STATE(11), 1,
      aux_sym_repeat_repeat1,
    STATE(23), 1,
      sym_repeat,
    ACTIONS(9), 2,
      sym_number,
      sym_string,
  [182] = 3,
    ACTIONS(7), 1,
      sym_component_separator,
    STATE(8), 1,
      aux_sym_repeat_repeat1,
    ACTIONS(35), 5,
      sym_field_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [196] = 1,
    ACTIONS(21), 7,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      sym_subcomponent_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [206] = 4,
    ACTIONS(37), 1,
      sym_field_separator,
    STATE(17), 1,
      aux_sym_msh_repeat1,
    STATE(31), 1,
      sym_segment_separator,
    ACTIONS(39), 3,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [221] = 4,
    ACTIONS(37), 1,
      sym_field_separator,
    STATE(24), 1,
      aux_sym_msh_repeat1,
    STATE(34), 1,
      sym_segment_separator,
    ACTIONS(39), 3,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [236] = 4,
    ACTIONS(37), 1,
      sym_field_separator,
    STATE(24), 1,
      aux_sym_msh_repeat1,
    STATE(35), 1,
      sym_segment_separator,
    ACTIONS(39), 3,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [251] = 3,
    ACTIONS(43), 1,
      sym_repetition_separator,
    STATE(19), 1,
      aux_sym_field_repeat1,
    ACTIONS(41), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [264] = 3,
    ACTIONS(43), 1,
      sym_repetition_separator,
    STATE(22), 1,
      aux_sym_field_repeat1,
    ACTIONS(45), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [277] = 4,
    ACTIONS(37), 1,
      sym_field_separator,
    STATE(16), 1,
      aux_sym_msh_repeat1,
    STATE(32), 1,
      sym_segment_separator,
    ACTIONS(39), 3,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [292] = 1,
    ACTIONS(26), 6,
      sym_field_separator,
      sym_component_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [301] = 3,
    ACTIONS(49), 1,
      sym_repetition_separator,
    STATE(22), 1,
      aux_sym_field_repeat1,
    ACTIONS(47), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [314] = 1,
    ACTIONS(47), 5,
      sym_field_separator,
      sym_repetition_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [322] = 3,
    ACTIONS(52), 1,
      sym_field_separator,
    STATE(24), 1,
      aux_sym_msh_repeat1,
    ACTIONS(55), 3,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [334] = 3,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_segment_name,
    STATE(25), 2,
      sym_segment,
      aux_sym_message_repeat1,
  [345] = 1,
    ACTIONS(55), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [352] = 3,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_segment_name,
    STATE(28), 2,
      sym_segment,
      aux_sym_message_repeat1,
  [363] = 3,
    ACTIONS(64), 1,
      sym_segment_name,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(25), 2,
      sym_segment,
      aux_sym_message_repeat1,
  [374] = 1,
    ACTIONS(68), 4,
      sym_field_separator,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_CR_LF,
  [381] = 1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [386] = 1,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [391] = 1,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [396] = 2,
    ACTIONS(76), 1,
      sym_component_separator,
    STATE(15), 1,
      sym_msh_controls,
  [403] = 1,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [408] = 1,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [413] = 1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
  [417] = 1,
    ACTIONS(84), 1,
      sym_escape_character,
  [421] = 1,
    ACTIONS(86), 1,
      sym_field_separator,
  [425] = 1,
    ACTIONS(88), 1,
      sym_subcomponent_separator,
  [429] = 1,
    ACTIONS(90), 1,
      sym_repetition_separator,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 95,
  [SMALL_STATE(8)] = 110,
  [SMALL_STATE(9)] = 124,
  [SMALL_STATE(10)] = 134,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 162,
  [SMALL_STATE(13)] = 182,
  [SMALL_STATE(14)] = 196,
  [SMALL_STATE(15)] = 206,
  [SMALL_STATE(16)] = 221,
  [SMALL_STATE(17)] = 236,
  [SMALL_STATE(18)] = 251,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 277,
  [SMALL_STATE(21)] = 292,
  [SMALL_STATE(22)] = 301,
  [SMALL_STATE(23)] = 314,
  [SMALL_STATE(24)] = 322,
  [SMALL_STATE(25)] = 334,
  [SMALL_STATE(26)] = 345,
  [SMALL_STATE(27)] = 352,
  [SMALL_STATE(28)] = 363,
  [SMALL_STATE(29)] = 374,
  [SMALL_STATE(30)] = 381,
  [SMALL_STATE(31)] = 386,
  [SMALL_STATE(32)] = 391,
  [SMALL_STATE(33)] = 396,
  [SMALL_STATE(34)] = 403,
  [SMALL_STATE(35)] = 408,
  [SMALL_STATE(36)] = 413,
  [SMALL_STATE(37)] = 417,
  [SMALL_STATE(38)] = 421,
  [SMALL_STATE(39)] = 425,
  [SMALL_STATE(40)] = 429,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [5] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_repeat_repeat1, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_repeat_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_repeat_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subcomponent, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_msh_controls, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment_separator, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msh, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msh, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hl7v2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hl7v2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
